<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Medicine;
use Carbon\Carbon;

class MedicineSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $medicines = [
            [
                'medicine_name' => 'Paracetamol',
                'generic_name' => 'Acetaminophen',
                'brand_name' => 'Tylenol',
                'manufacturer' => 'Johnson & Johnson',
                'category' => 'Pain Relief',
                'description' => 'Pain reliever and fever reducer',
                'dosage_form' => 'Tablet',
                'strength' => '500mg',
                'unit' => 'pieces',
                'stock_quantity' => 150,
                'minimum_stock' => 20,
                'unit_price' => 0.50,
                'selling_price' => 1.00,
                'supplier' => 'PharmaCorp Ltd.',
                'batch_number' => 'PC2024001',
                'manufacturing_date' => '2024-01-15',
                'expiry_date' => '2026-01-15',
                'storage_conditions' => 'Store in a cool, dry place',
                'side_effects' => 'Nausea, skin rash (rare)',
                'contraindications' => 'Severe liver disease',
                'requires_prescription' => false,
                'status' => 'active',
            ],
            [
                'medicine_name' => 'Amoxicillin',
                'generic_name' => 'Amoxicillin',
                'brand_name' => 'Amoxil',
                'manufacturer' => 'GlaxoSmithKline',
                'category' => 'Antibiotics',
                'description' => 'Broad-spectrum antibiotic',
                'dosage_form' => 'Capsule',
                'strength' => '250mg',
                'unit' => 'pieces',
                'stock_quantity' => 8,
                'minimum_stock' => 15,
                'unit_price' => 2.00,
                'selling_price' => 3.50,
                'supplier' => 'MediSupply Inc.',
                'batch_number' => 'AMX2024002',
                'manufacturing_date' => '2024-02-10',
                'expiry_date' => '2025-02-10',
                'storage_conditions' => 'Store at room temperature',
                'side_effects' => 'Diarrhea, nausea, allergic reactions',
                'contraindications' => 'Penicillin allergy',
                'requires_prescription' => true,
                'status' => 'active',
            ],
            [
                'medicine_name' => 'Vitamin C',
                'generic_name' => 'Ascorbic Acid',
                'brand_name' => 'Redoxon',
                'manufacturer' => 'Bayer',
                'category' => 'Vitamins & Supplements',
                'description' => 'Vitamin C supplement for immune support',
                'dosage_form' => 'Tablet',
                'strength' => '1000mg',
                'unit' => 'pieces',
                'stock_quantity' => 75,
                'minimum_stock' => 10,
                'unit_price' => 0.75,
                'selling_price' => 1.25,
                'supplier' => 'VitaHealth Supply',
                'batch_number' => 'VC2024003',
                'manufacturing_date' => '2024-03-01',
                'expiry_date' => '2026-03-01',
                'storage_conditions' => 'Store in a cool, dry place away from light',
                'side_effects' => 'Stomach upset in large doses',
                'contraindications' => 'Kidney stones history',
                'requires_prescription' => false,
                'status' => 'active',
            ],
            [
                'medicine_name' => 'Cough Syrup',
                'generic_name' => 'Dextromethorphan',
                'brand_name' => 'Robitussin',
                'manufacturer' => 'Pfizer',
                'category' => 'Cold & Flu',
                'description' => 'Cough suppressant syrup',
                'dosage_form' => 'Syrup',
                'strength' => '15mg/5ml',
                'unit' => 'bottles',
                'stock_quantity' => 25,
                'minimum_stock' => 5,
                'unit_price' => 4.50,
                'selling_price' => 7.50,
                'supplier' => 'ColdCare Distributors',
                'batch_number' => 'CS2024004',
                'manufacturing_date' => '2024-01-20',
                'expiry_date' => '2025-01-20',
                'storage_conditions' => 'Store at room temperature',
                'side_effects' => 'Drowsiness, dizziness',
                'contraindications' => 'MAOI use, children under 4',
                'requires_prescription' => false,
                'status' => 'active',
            ],
            [
                'medicine_name' => 'Insulin',
                'generic_name' => 'Human Insulin',
                'brand_name' => 'Humulin',
                'manufacturer' => 'Eli Lilly',
                'category' => 'Diabetes',
                'description' => 'Fast-acting insulin for diabetes management',
                'dosage_form' => 'Injection',
                'strength' => '100IU/ml',
                'unit' => 'vials',
                'stock_quantity' => 12,
                'minimum_stock' => 8,
                'unit_price' => 25.00,
                'selling_price' => 40.00,
                'supplier' => 'Diabetes Care Supply',
                'batch_number' => 'INS2024005',
                'manufacturing_date' => '2024-04-01',
                'expiry_date' => '2025-04-01',
                'storage_conditions' => 'Refrigerate at 2-8°C',
                'side_effects' => 'Hypoglycemia, injection site reactions',
                'contraindications' => 'Hypoglycemia episodes',
                'requires_prescription' => true,
                'status' => 'active',
            ],
            [
                'medicine_name' => 'Aspirin',
                'generic_name' => 'Acetylsalicylic Acid',
                'brand_name' => 'Bayer Aspirin',
                'manufacturer' => 'Bayer',
                'category' => 'Pain Relief',
                'description' => 'Pain reliever and blood thinner',
                'dosage_form' => 'Tablet',
                'strength' => '81mg',
                'unit' => 'pieces',
                'stock_quantity' => 200,
                'minimum_stock' => 25,
                'unit_price' => 0.25,
                'selling_price' => 0.50,
                'supplier' => 'Generic Pharma',
                'batch_number' => 'ASP2024006',
                'manufacturing_date' => '2024-02-15',
                'expiry_date' => '2027-02-15',
                'storage_conditions' => 'Store at room temperature',
                'side_effects' => 'Stomach irritation, bleeding risk',
                'contraindications' => 'Bleeding disorders, children with viral infections',
                'requires_prescription' => false,
                'status' => 'active',
            ],
            [
                'medicine_name' => 'Expired Medicine Example',
                'generic_name' => 'Old Formula',
                'brand_name' => 'ExpiredBrand',
                'manufacturer' => 'Old Pharma',
                'category' => 'General',
                'description' => 'This is an example of expired medicine',
                'dosage_form' => 'Tablet',
                'strength' => '100mg',
                'unit' => 'pieces',
                'stock_quantity' => 5,
                'minimum_stock' => 10,
                'unit_price' => 1.00,
                'selling_price' => 2.00,
                'supplier' => 'Old Supplier',
                'batch_number' => 'EXP2023001',
                'manufacturing_date' => '2023-01-01',
                'expiry_date' => '2024-01-01',
                'storage_conditions' => 'Store in cool place',
                'requires_prescription' => true,
                'status' => 'expired',
            ],
        ];
        
        foreach ($medicines as $medicineData) {
            Medicine::create($medicineData);
        }
        
        echo "Sample medicines created successfully!\n";
        echo "- 7 medicines added with various categories\n";
        echo "- Includes low stock and expired examples\n";
        echo "- Mix of prescription and over-the-counter medicines\n";
    }
}
