databases:
  - name: bokod-cms-db
    databaseName: bokod_cms
    user: bokod_user
    region: oregon

services:
  - type: web
    name: bokod-cms
    runtime: php
    buildCommand: "./render-build.sh"
    startCommand: "php artisan serve --host=0.0.0.0 --port=$PORT"
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_STACK
        value: single
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: bokod-cms-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: bokod-cms-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: bokod-cms-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: bokod-cms-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: bokod-cms-db
          property: password